name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - hufilter*.txt

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out to repository
        uses: actions/checkout@v4

      - name: Make gh-pages folder
        run: mkdir gh-pages

      - name: Copy .txt files with hufilter prefix to gh-pages folder
        run: cp hufilter*.txt gh-pages/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
